#!/bin/bash
sed -i 's/15.2.28.0/'"$BUILD_NUMBER"'/' version.h
export CMAKE_PREFIX_PATH=~/nfs_storage/pkgs/usr
/usr/intel/pkgs/cmake/2.8.10.2/bin/cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=/usr/intel/pkgs/gcc/4.8.2/bin/g++ -DCMAKE_BUILD_TYPE=Release
make
